jembi/JeMPI

JeMPI_Apps/JeMPI_API/.gitignore
JeMPI_Apps/JeMPI_API/build.sh
JeMPI_Apps/JeMPI_API/pom.xml
JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/API.java
JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/HttpServer.java
JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/JsonFieldsConfig.java
JeMPI_Apps/JeMPI_Configuration/config-reference.json
documentation/SUMMARY.md
documentation/api.md

Adds an endpoint that returns the json field config for JeMPI UI.
JIRA Ticket : https://jembiprojects.jira.com/browse/JMPI-414

feat: Add fields endpoint

---

JeMPI_Apps/JeMPI_Configuration/config-reference.json

This PR fixes the field names to be in snake case as it's required by the code generator.

fix: fix fields snake case

---

JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/BackEnd.java
JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/HttpServer.java
docker/conf/stack/docker-stack-0.yml
docker/conf/stack/docker-stack-1.yml

- This PR adds the endpoint for importing patient record from a CSV file.

JMPI-66: Create Bulk Import endpoint

---

.github/workflows/build.yml

create maven build github workflow

create github workflow

---

JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/LibMPI.java
JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/LibMPIClientInterface.java
JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/dgraph/DgraphMutations.java
JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/dgraph/LibDgraph.java
JeMPI_Apps/JeMPI_Linker/pom.xml
JeMPI_Apps/JeMPI_Linker/src/main/java/org/jembi/jempi/linker/BackEnd.java
JeMPI_Apps/JeMPI_Linker/src/test/java/org/jembi/jempi/linker/LinkerTest.java
JeMPI_Apps/pom.xml

this is branched from main, it adds recompute score featre and its unit test

Jmpi 173 recompute scores new

---

launch-local.sh

maven package is required before building images of each component

hotfix build script

---

JeMPI_Apps/JeMPI_Shared/src/main/java/org/jembi/jempi/shared/utils/AppUtils.java

Removed a check in the if statement that gets the names from the CustomDemographicData class.

Jmpi 516 fix app utils get names

---

JeMPI_Apps/JeMPI_AsyncReceiver/src/main/java/org/jembi/jempi/async_receiver/CustomMain.java
JeMPI_Apps/JeMPI_AsyncReceiver/src/main/java/org/jembi/jempi/async_receiver/Main.java
JeMPI_Apps/JeMPI_Shared/src/main/java/org/jembi/jempi/shared/models/BatchMetaData.java

Create BatchMetaData class to store sentinel values for each batch import for tracking and reporting

JMPI-501 batch metadata

---

JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/HttpServer.java
JeMPI_Apps/JeMPI_Configuration/config-reference.json
JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/dgraph/CustomDgraphConstants.java
JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/dgraph/DgraphQueries.java

Update Dgraph search function for exact search to use fulltext to allow case insensitive search

JMPI-493 case sensitive search

---

JeMPI_Apps/JeMPI_Configuration/config-reference.json
JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/dgraph/CustomDgraphConstants.java
JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/dgraph/DgraphQueries.java

update exact match to use regexp instead of alloftext

JMPI-493 case insensitive search

---

README.md
documentation/installation/standalone-installation.md

Update Java version in documentation to the one currently in use : Temurin-17.0.6+10

docs: update java version

---

documentation/installation/standalone-installation.md

Add launch-local installation option

JMPI-549 update installation guide

---

JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/BackEnd.java
JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/HttpServer.java
JeMPI_Apps/JeMPI_API/src/main/resources/config-api.json
JeMPI_Apps/JeMPI_Configuration/config-reference-api.json
JeMPI_Apps/JeMPI_ETL/pom.xml
JeMPI_Apps/JeMPI_Shared/pom.xml

- this PR removes the fhir references from jempi-base

JMPI-571 remove fhir references

---

JeMPI_Apps/JeMPI_Configuration/config-reference-api.json
JeMPI_Apps/JeMPI_UI/src/components/linkedRecords/LinkedRecords.tsx
JeMPI_Apps/JeMPI_UI/src/components/reviewMatches/DataGrid.tsx
JeMPI_Apps/JeMPI_UI/src/components/reviewMatches/Dialog.tsx
JeMPI_Apps/JeMPI_UI/src/components/reviewMatches/ReviewLink.tsx
JeMPI_Apps/JeMPI_UI/src/components/reviewMatches/SearchModal.tsx
JeMPI_Apps/JeMPI_UI/src/utils/constants.ts

- this PR add minor changes to the UI + fix issue with the config reference

JMPI-634 minor changes + config reference

---

JeMPI_Apps/JeMPI_Configuration/reference/config-reference-link-d-validate-dp-match-dp.json
JeMPI_Apps/JeMPI_LibMPI/src/main/java/org/jembi/jempi/libmpi/lib/hooks/indexes/LibMPIIndexesHooks.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/utils/AuditTrailBridge.java
JeMPI_Apps/JeMPI_Linker/src/main/java/org/jembi/jempi/linker/SPInteractions.java

disable match streaming

---

JeMPI_Apps/JeMPI_UI/src/components/notificationWorklist/NotificationWorklist.tsx
JeMPI_Apps/JeMPI_UI/src/components/shared/SelectDropdown.tsx
JeMPI_Apps/JeMPI_UI/src/services/ApiClient.ts
JeMPI_Apps/JeMPI_UI/src/types/Notification.ts

Added All option to notification state options
Navigate to http://localhost:3000/notifications
Select an option on the states filter

Jmpi-bug-open-closed-notifications-filter-does-not-work-properly

---

JeMPI_Apps/JeMPI_LibAPI/src/main/java/org/jembi/jempi/libapi/Routes.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/GlobalConstants.java
documentation/JeMPI.postman_collection.json

**Summary**:
**Added 4 new search endpoints for simple search and customer search:**
1. simpleGoldenSearch
2. simpleInteractionPatientSearch
3. customGoldenSearch
4. customInteractionPatientSearch
Removed old search and customSearch endpoints.

Refactor search end-points for simple and custom search

---

JeMPI_Apps/JeMPI_UI/src/components/dashboard/Dashboard.tsx
JeMPI_Apps/JeMPI_UI/src/config/index.ts
JeMPI_Apps/JeMPI_UI/src/services/ApiClient.ts
JeMPI_Apps/JeMPI_UI/src/services/apiRoutes.ts

added configuration data file in services
created fetch configuration end point
added unit test for end point
npm run test

Cu 86byc5x3c create get configuration endpoint

---

JeMPI_Apps/JeMPI_AsyncReceiver/src/main/java/org/jembi/jempi/async_receiver/Main.java
JeMPI_Apps/JeMPI_Controller/src/main/java/org/jembi/jempi/controller/SPInteractions.java
JeMPI_Apps/JeMPI_ETL/src/main/java/org/jembi/jempi/etl/CustomSourceRecordStream.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/AsyncReceiverMetadata.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/CommonMetaData.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/ControllerMetadata.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/ETLMetadata.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/InteractionEnvelop.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/LinkerMetadata.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/SessionMetadata.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/models/UIMetadata.java
JeMPI_Apps/JeMPI_LibShared/src/main/java/org/jembi/jempi/shared/utils/AppUtils.java
JeMPI_Apps/JeMPI_Linker/src/main/java/org/jembi/jempi/linker/SPInteractions.java
JeMPI_Apps/JeMPI_Linker/src/main/java/org/jembi/jempi/linker/backend/BackEnd.java

Create new metadata classes for each component and update start and end datetime on start and end sentinels

Refactor interaction envelop

---

JeMPI_Apps/JeMPI_UI/jest.config.js
JeMPI_Apps/JeMPI_UI/src/components/error/ApiErrorMessage.tsx
JeMPI_Apps/JeMPI_UI/src/test/error/ApiErrorMessage.test.tsx
JeMPI_Apps/JeMPI_UI/src/test/error/NotFound.test.tsx

added unit tests for not found and api error message
npm test

added unit test for notfound and api error message
